### ISSUE TITLE
Lições aprendidas

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-Matriculai#13]
Registrem mais detalhes sobre a aprendizagem da equipe, suas felicidades e dificuldades durante a unidade, assim como, o que fizeram para solucionar as questões.

**Comment by luanasoares0901** [comment]
![image](https://github.com/mdsreq-fga-unb/2023.2-Matriculai/assets/82223911/30b6a43c-be4c-4900-aa11-e17f4ab8eeb7)
