### ISSUE TITLE
Requisitos não funcionais

### ISSUE THREAD

**Issue by juliaryoshida** [mdsreq-fga-unb/2023.2-Matriculai#17]
- Usabilidade e interface são a mesma coisa na URPS
- Especificar o requisito, não estão verificáveis

**Comment by luanasoares0901** [comment]
![image](https://github.com/mdsreq-fga-unb/2023.2-Matriculai/assets/82223911/d76e37d6-725f-4d76-9848-0dd9ae8522f1)
