### ISSUE TITLE
Objetivos

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-Matriculai#3]
- Facilitar o desempenho organizacional da gestão da escola;
- Auxiliar na adaptação dos alunos e da escola ao novo Ensino Médio.

**Considerações:**
1. o problema está voltado a gestão de matrículas, mas nos objetivos vcs falam em gestão da escola. Isso é muito amplo. A gestão da escola envolve muitas coisas, podendo incluir as matrículas.
2. não está claro como a gestão de matrículas pode auxiliar na adaptação dos estudantes.
3. Os objetivos precisam ser passíveis de comprovação. Como esperam 'provar' que objetivos tão genéricos foram atingidos?

**Comment by luanasoares0901** [comment]
O objetivo principal do Matriculaí é a transformação digital do processo de matrículas em disciplinas do CEMTN, solucionando o problema de dificuldade na gestão da matrícula dos alunos, tanto para os coordenadores organizarem as matrículas e relacioná-las aos estudantes, quanto para os próprios alunos em si, ao realizarem sua escolha de disciplinas e visualizarem sua grade horária.
