### ISSUE TITLE
Organização do projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-Matriculai#4]
Vcs estão na disciplina de REQ.
Nenhum dos papéis e atribuições apresentadas pela equipe, refere-se aos papéis e atividades de REQ.

![image](https://github.com/mdsreq-fga-unb/2023.2-Matriculai/assets/68402547/cef0f073-4b80-47e6-8935-a33a935e8307)

**Comment by luanasoares0901** [comment]
![image](https://github.com/mdsreq-fga-unb/2023.2-Matriculai/assets/82223911/83ca9a1d-0b04-4681-8e53-323397cc2ba7)
